spring:
  application:
    name: SERVICES-OFFERING
  datasource:
    url: jdbc:mysql://localhost:3306/services_offering
    username: root
    password: ab12+-34
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8083
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
