spring:
  application:
    name: BOOKING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: ben
    password: ben

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka