spring:
  application:
    name: BOOKING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/bookings
    username: ben
    password: ben

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085